[tool.ruff]
line-length = 100
target-version = "py311"

select = [
  "F",      # pyflakes (ошибки в коде)
  "E", "W", # pycodestyle
  "I",      # isort
  "UP",     # pyupgrade
  "B",      # bugbear
  "TCH",    # typing imports
  "TID",    # typing style
    # аннотации (только если хочешь частично типовую проверку)
]

ignore = [
  "B008",   # не ругаться на вызов mutable default
]

[tool.mypy]
strict = false
ignore_missing_imports = true
check_untyped_defs = false
disallow_untyped_defs = false
disallow_incomplete_defs = false
disallow_untyped_calls = false
warn_return_any = false
warn_unused_ignores = false
